<?php

return [

    'ar' => [
        // Navigation/sidebar
        'dashboard'      => 'لوحة التحكم',
        'nav_products'   => 'المنتجات',
        'nav_customers'  => 'العملاء',
        'nav_sales'      => 'المبيعات',
        'nav_debts'      => 'الديون',
        'nav_inventory'  => 'جرد المخزن',
        'nav_new_sale'   => 'بيع جديد',
        'system_ok'      => 'النظام يعمل',

        // Common actions
        'search'         => 'بحث',
        'filter'         => 'تصفية',
        'clear'          => 'مسح',
        'edit'           => 'تعديل',
        'delete'         => 'حذف',
        'view'           => 'عرض',
        'add'            => 'إضافة',
        'save'           => 'حفظ',
        'save_changes'   => 'حفظ التغييرات',
        'back'           => 'رجوع',
        'actions'        => 'الإجراءات',
        'cancel'         => 'إلغاء',

        // Status/type labels
        'cash'           => 'نقد',
        'debt'           => 'دين',
        'installments'   => 'أقساط',
        'completed'      => 'مكتمل',
        'open'           => 'مفتوح',
        'all'            => 'الكل',
        'guest'          => 'زبون عابر',

        // Field labels
        'name'           => 'الاسم',
        'phone'          => 'الهاتف',
        'address'        => 'العنوان',
        'currency'       => 'العملة',
        'number'         => 'الرقم',
        'customer'       => 'العميل',
        'type'           => 'النوع',
        'product'        => 'المنتج',
        'quantity'       => 'الكمية',
        'price'          => 'السعر',
        'total'          => 'الإجمالي',
        'balance'        => 'الرصيد',
        'paid'           => 'المدفوع',
        'date'           => 'التاريخ',
        'status'         => 'الحالة',
        'notes'          => 'ملاحظات',
        'category'       => 'الفئة',
        'stock'          => 'المخزون',
        'buy_price'      => 'سعر الشراء',
        'sell_price'     => 'سعر البيع',

        // Dashboard
        'today_sales'         => 'مبيعات اليوم',
        'today_revenue'       => 'إيرادات اليوم',
        'total_debts'         => 'إجمالي الديون',
        'total_stock'         => 'إجمالي المخزون',
        'today_transactions'  => 'معاملات اليوم',
        'today_total_paid'    => 'إجمالي المدفوع اليوم',
        'latest_sales'        => 'آخر المبيعات',
        'no_sales_yet'        => 'لا توجد مبيعات بعد',

        // Inventory
        'total_pieces'       => 'إجمالي القطع',
        'stock_cost'         => 'تكلفة المخزن',
        'sell_value'         => 'قيمة البيع',
        'needs_restock'      => 'يحتاج إعادة تخزين',
        'out_of_stock'       => 'نفد من المخزن',
        'low_stock'          => 'مخزون منخفض',
        'good_stock'         => 'مخزون كافٍ',
        'stock_ok'           => 'المخزن ممتاز',
        'out_of_stock_badge' => 'نفد',
        'low_badge'          => 'منخفض',
        'available_badge'    => 'متوفر',
        'stock_report'       => 'كشف المخزون',
        'stock_value'        => 'قيمة المخزون',
        'sorted_asc'         => 'مرتب من الأقل للأكثر مخزوناً',

        // Debts
        'total_debts_iqd'  => 'إجمالي الديون (IQD)',
        'total_debts_usd'  => 'إجمالي الديون (USD)',
        'open_debts'       => 'الديون المفتوحة',
        'no_open_debts'    => 'لا توجد ديون مفتوحة!',
        'all_complete'     => 'جميع المبيعات مكتملة.',
        'add_payment'      => 'إضافة دفعة',
        'payment_history'  => 'سجل الدفعات',
        'amount'           => 'المبلغ',
        'payment'          => 'دفعة',

        // Products
        'products_list'    => 'قائمة المنتجات',
        'add_product'      => 'إضافة منتج',
        'search_product'   => 'بحث عن منتج',
        'no_products'      => 'لا توجد منتجات. أضف المنتج الأول!',
        'product_name'     => 'اسم المنتج',
        'edit_product'     => 'تعديل منتج',
        'add_product_new'  => 'إضافة منتج جديد',
        'cost_secret'      => 'سعر التكلفة (سري)',
        'price_for_customers' => 'السعر المعروض للعملاء',

        // Customers
        'customers_list'       => 'قائمة العملاء',
        'add_customer'         => 'إضافة عميل',
        'search_customer'      => 'بحث عن عميل',
        'no_customers'         => 'لا يوجد عملاء بعد.',
        'preferred_currency'   => 'العملة المفضلة',
        'full_name'            => 'الاسم الكامل',
        'sales_count'          => 'المبيعات',
        'total_sales'          => 'إجمالي المبيعات',
        'no_debt'              => 'لا يوجد دين',
        'no_debt_detail'       => 'هذا العميل ليس عليه دين',
        'sales_history'        => 'سجل المبيعات',
        'no_sales_for_customer'=> 'لا توجد مبيعات لهذا العميل بعد.',
        'new_sale'             => 'بيع جديد',
        'whatsapp_statement'   => 'إرسال كشف الحساب واتساب',
        'edit_customer'        => 'تعديل عميل',
        'add_customer_new'     => 'إضافة عميل جديد',
        'optional'             => 'اختياري',
        'optional_notes'       => 'ملاحظات إضافية...',

        // Sales
        'sales_list'          => 'قائمة المبيعات',
        'new_sale_form'       => 'بيع جديد',
        'no_sales'            => 'لا توجد مبيعات.',
        'payment_type'        => 'نوع الدفع',
        'cash_now'            => 'الدفع الفوري',
        'pay_later'           => 'يسدد لاحقاً',
        'installment_pay'     => 'دفع بالأقساط',
        'products_sold'       => 'المنتجات المباعة',
        'add_product_row'     => 'إضافة منتج',
        'select_product'      => 'اختر منتجاً',
        'grand_total'         => 'المجموع الكلي',
        'payment_details'     => 'تفاصيل الدفع',
        'full_payment_now'    => 'سيتم دفع المبلغ كاملاً فوراً.',
        'amount_paid_now'     => 'المبلغ المدفوع الآن',
        'zero_full_debt'      => '0 = دين كامل، أو أدخل دفعة مقدمة',
        'remaining_balance'   => 'الرصيد المتبقي:',
        'first_installment'   => 'الدفعة الأولى (العربون)',
        'num_installments'    => 'عدد الأقساط',
        'interval'            => 'الفترة بين الأقساط',
        'weekly'              => 'كل أسبوع (7 أيام)',
        'biweekly'            => 'كل أسبوعين (14 يوم)',
        'monthly'             => 'كل شهر (30 يوم)',
        'bimonthly'           => 'كل شهرين',
        'first_installment_date' => 'تاريخ القسط الأول',
        'per_installment'     => 'كل قسط:',
        'installment_formula' => 'الرصيد بعد العربون ÷ عدد الأقساط',
        'save_sale'           => 'حفظ العملية',
        'invoice'             => 'فاتورة',
        'sale_customer'       => 'العميل',
        'payment_type_label'  => 'نوع الدفع',
        'currency_label'      => 'العملة',
        'total_label'         => 'الإجمالي',
        'amount_paid_label'   => 'المبلغ المدفوع',
        'outstanding_label'   => 'الرصيد المتبقي',
        'settled'             => '✓ مسدد',
        'delete_sale'         => 'حذف البيع',
        'back_to_sales'       => '→ رجوع للمبيعات',
        'installment_plan'    => 'خطة الأقساط',
        'num_install'         => 'عدد الأقساط',
        'each_install'        => 'كل قسط',
        'first_install_date'  => 'القسط الأول',
        'period_days'         => 'الفترة',
        'days'                => 'يوم',
        'invoice_total'       => 'المجموع:',
        'delete_confirm'      => 'هل تريد حذف هذا البيع؟',

        // Confirm dialogs
        'confirm_delete_product'  => 'هل تريد حذف هذا المنتج؟',
        'confirm_delete_customer' => 'هل تريد حذف هذا العميل؟',
    ],

    'ku_sorani' => [
        // Navigation/sidebar
        'dashboard'      => 'داشبۆرد',
        'nav_products'   => 'کاڵاکان',
        'nav_customers'  => 'کڕیارەکان',
        'nav_sales'      => 'فرۆشتنەکان',
        'nav_debts'      => 'قەرزەکان',
        'nav_inventory'  => 'ژمارکردنی کۆگا',
        'nav_new_sale'   => 'فرۆشتنی نوێ',
        'system_ok'      => 'سیستەم کارئەکات',

        // Common actions
        'search'         => 'گەڕان',
        'filter'         => 'فلتەر',
        'clear'          => 'پاككردنەوە',
        'edit'           => 'دەستکاریکردن',
        'delete'         => 'سڕینەوە',
        'view'           => 'بینین',
        'add'            => 'زیادکردن',
        'save'           => 'پاشەکەوتکردن',
        'save_changes'   => 'پاشەکەوتکردنی گۆڕانکاری',
        'back'           => 'گەڕانەوە',
        'actions'        => 'کردارەکان',
        'cancel'         => 'پاشگەزبوونەوە',

        // Status/type labels
        'cash'           => 'نەقد',
        'debt'           => 'قەرز',
        'installments'   => 'قیست',
        'completed'      => 'تەواوبوو',
        'open'           => 'کراوەیە',
        'all'            => 'هەموو',
        'guest'          => 'کڕیاری مێوان',

        // Field labels
        'name'           => 'ناو',
        'phone'          => 'مۆبایل',
        'address'        => 'ناونیشان',
        'currency'       => 'دراو',
        'number'         => 'ژمارە',
        'customer'       => 'کڕیار',
        'type'           => 'جۆر',
        'product'        => 'کاڵا',
        'quantity'       => 'ژمارەی دانە',
        'price'          => 'نرخ',
        'total'          => 'کۆی گشتی',
        'balance'        => 'ماوە',
        'paid'           => 'دراوی',
        'date'           => 'بەروار',
        'status'         => 'دۆخ',
        'notes'          => 'تێبینی',
        'category'       => 'جۆر',
        'stock'          => 'کۆگا',
        'buy_price'      => 'نرخی کڕین',
        'sell_price'     => 'نرخی فرۆشتن',

        // Dashboard
        'today_sales'         => 'فرۆشتنی ئەمڕۆ',
        'today_revenue'       => 'داهاتی ئەمڕۆ',
        'total_debts'         => 'کۆی قەرزەکان',
        'total_stock'         => 'کۆی کۆگا',
        'today_transactions'  => 'مامەڵەی ئەمڕۆ',
        'today_total_paid'    => 'کۆی دراوی ئەمڕۆ',
        'latest_sales'        => 'دوایین فرۆشتنەکان',
        'no_sales_yet'        => 'هێشتا فرۆشتنێک نیە',

        // Inventory
        'total_pieces'       => 'کۆی دانەکان',
        'stock_cost'         => 'تێچووی کۆگا',
        'sell_value'         => 'بەهای فرۆشتن',
        'needs_restock'      => 'پێویستی دۆخی کۆگا',
        'out_of_stock'       => 'کۆگا خاوی',
        'low_stock'          => 'کۆگا کەم',
        'good_stock'         => 'کۆگا باش',
        'stock_ok'           => 'کۆگا ئەمڕۆ باشە',
        'out_of_stock_badge' => 'تەواوبوو',
        'low_badge'          => 'کەم',
        'available_badge'    => 'هەیە',
        'stock_report'       => 'ڕاپۆرتی کۆگا',
        'stock_value'        => 'بەهای کۆگا',
        'sorted_asc'         => 'ڕیزکراوە لە کەمەوە بۆ زیاتر',

        // Debts
        'total_debts_iqd'  => 'کۆی قەرزەکان (IQD)',
        'total_debts_usd'  => 'کۆی قەرزەکان (USD)',
        'open_debts'       => 'قەرزی کراوەکان',
        'no_open_debts'    => 'هیچ قەرزێکی کراوە نیە!',
        'all_complete'     => 'هەموو فرۆشتنەکان تەواوبوون.',
        'add_payment'      => 'دراوێک زیادبکە',
        'payment_history'  => 'مێژووی دراوەکان',
        'amount'           => 'مەبەڵەغ',
        'payment'          => 'دراوێک',

        // Products
        'products_list'    => 'لیستی کاڵاکان',
        'add_product'      => 'کاڵایەک زیادبکە',
        'search_product'   => 'بگەڕێ بۆ کاڵا',
        'no_products'      => 'هیچ کاڵایەک نییە. یەکەمیان زیادبکە!',
        'product_name'     => 'ناوی کاڵا',
        'edit_product'     => 'دەستکاریکردنی کاڵا',
        'add_product_new'  => 'کاڵایەکی نوێ زیادبکە',
        'cost_secret'      => 'نرخی تێچوون (نهێنی)',
        'price_for_customers' => 'نرخی بۆ کڕیارەکان',

        // Customers
        'customers_list'       => 'لیستی کڕیارەکان',
        'add_customer'         => 'کڕیارێک زیادبکە',
        'search_customer'      => 'بگەڕێ بۆ کڕیار',
        'no_customers'         => 'هیچ کڕیارێک نییە.',
        'preferred_currency'   => 'دراوی دڵخواز',
        'full_name'            => 'ناوی تەواو',
        'sales_count'          => 'فرۆشتن',
        'total_sales'          => 'کۆی فرۆشتنەکان',
        'no_debt'              => 'قەرزی نیە',
        'no_debt_detail'       => 'ئەم کڕیارە قەرزی نیە',
        'sales_history'        => 'مێژووی فرۆشتنەکان',
        'no_sales_for_customer'=> 'هیچ فرۆشتنێک بۆ ئەم کڕیارە نیە.',
        'new_sale'             => 'فرۆشتنی نوێ',
        'whatsapp_statement'   => 'پێرستی هەژمار بنێرە واتساپ',
        'edit_customer'        => 'دەستکاریکردنی کڕیار',
        'add_customer_new'     => 'کڕیارێکی نوێ زیادبکە',
        'optional'             => 'دڵخواز',
        'optional_notes'       => 'تێبینیی زیادە...',

        // Sales
        'sales_list'          => 'لیستی فرۆشتنەکان',
        'new_sale_form'       => 'فرۆشتنی نوێ',
        'no_sales'            => 'هیچ فرۆشتنێک نییە.',
        'payment_type'        => 'جۆری دراودان',
        'cash_now'            => 'دراودانی ئەسڵ',
        'pay_later'           => 'دواتر دەدات',
        'installment_pay'     => 'قیستەکانەوە',
        'products_sold'       => 'کاڵاکانی فرۆشراو',
        'add_product_row'     => 'کاڵا زیادبکە',
        'select_product'      => 'کاڵایەک هەڵبژێرە',
        'grand_total'         => 'کۆی گشتی',
        'payment_details'     => 'وردەکاری دراودان',
        'full_payment_now'    => 'هەموو مەبەڵەغەکە ئێستا دەدرێت.',
        'amount_paid_now'     => 'مەبەڵەغی دراو ئێستا',
        'zero_full_debt'      => '0 = قەرزی تەواو، یان پەیشەکی زیادبکە',
        'remaining_balance'   => 'ماوەی قەرز:',
        'first_installment'   => 'یەکەمین قیست (بیانە)',
        'num_installments'    => 'ژمارەی قیستەکان',
        'interval'            => 'کاتی نێوان قیستەکان',
        'weekly'              => 'هەفتەیەک جار (7 رۆژ)',
        'biweekly'            => 'دوو هەفتەیەک جار',
        'monthly'             => 'مانگێک جار (30 رۆژ)',
        'bimonthly'           => 'دوو مانگێک جار',
        'first_installment_date' => 'بەروارێ یەکەمین قیست',
        'per_installment'     => 'هەر قیستێک:',
        'installment_formula' => 'ماوە دوای بیانە ÷ ژمارەی قیستەکان',
        'save_sale'           => 'فرۆشتنەکە پاشەکەوتبکە',
        'invoice'             => 'پسوولە',
        'sale_customer'       => 'کڕیار',
        'payment_type_label'  => 'جۆری دراودان',
        'currency_label'      => 'دراو',
        'total_label'         => 'کۆی گشتی',
        'amount_paid_label'   => 'دراوی دراو',
        'outstanding_label'   => 'ماوەی قەرز',
        'settled'             => '✓ دراودراو',
        'delete_sale'         => 'فرۆشتنەکە بسڕەوە',
        'back_to_sales'       => '→ گەڕانەوە بۆ فرۆشتنەکان',
        'installment_plan'    => 'پلانی قیستەکان',
        'num_install'         => 'ژمارەی قیستەکان',
        'each_install'        => 'هەر قیستێک',
        'first_install_date'  => 'یەکەمین قیست',
        'period_days'         => 'ماوە',
        'days'                => 'رۆژ',
        'invoice_total'       => 'کۆی گشتی:',
        'delete_confirm'      => 'ئایا دەتەوێت ئەم فرۆشتنە بسڕیتەوە؟',

        // Confirm dialogs
        'confirm_delete_product'  => 'ئایا دەتەوێت ئەم کاڵایە بسڕیتەوە؟',
        'confirm_delete_customer' => 'ئایا دەتەوێت ئەم کڕیارە بسڕیتەوە؟',
    ],

    'ku_badini' => [
        // Navigation/sidebar
        'dashboard'      => 'داشبۆرد',
        'nav_products'   => 'شتەمەنیکان',
        'nav_customers'  => 'مشتەریان',
        'nav_sales'      => 'فرۆشتن',
        'nav_debts'      => 'قەرزان',
        'nav_inventory'  => 'ژمارکردنی مالخانه‌',
        'nav_new_sale'   => 'فرۆشتنی نو',
        'system_ok'      => 'سیستەم کاردەکات',

        // Common actions
        'search'         => 'گەریان',
        'filter'         => 'فلتەر',
        'clear'          => 'پاككردن',
        'edit'           => 'گوهرین',
        'delete'         => 'ژێبردن',
        'view'           => 'بینین',
        'add'            => 'زیادکردن',
        'save'           => 'پاراستن',
        'save_changes'   => 'پاراستنی گوهرین',
        'back'           => 'گەریانەوە',
        'actions'        => 'کردارەکان',
        'cancel'         => 'پاشگەزبوون',

        // Status/type labels
        'cash'           => 'نەقد',
        'debt'           => 'قەرز',
        'installments'   => 'قسط',
        'completed'      => 'تەواو',
        'open'           => 'کراوە',
        'all'            => 'هەموو',
        'guest'          => 'مشتەری مێوان',

        // Field labels
        'name'           => 'ناو',
        'phone'          => 'تەلەفۆن',
        'address'        => 'ناونیشان',
        'currency'       => 'دراو',
        'number'         => 'ژمارە',
        'customer'       => 'مشتەری',
        'type'           => 'جۆر',
        'product'        => 'شتەمەنی',
        'quantity'       => 'ئاسۆ',
        'price'          => 'نرخ',
        'total'          => 'کۆی گشتی',
        'balance'        => 'ماوە',
        'paid'           => 'پارەدراو',
        'date'           => 'رووژ',
        'status'         => 'حال',
        'notes'          => 'تێبینی',
        'category'       => 'جۆر',
        'stock'          => 'مالخانه‌',
        'buy_price'      => 'نرخی کڕین',
        'sell_price'     => 'نرخی فرۆشتن',

        // Dashboard
        'today_sales'         => 'فرۆشتنی ئەمڕۆ',
        'today_revenue'       => 'دەرئامەدی ئەمڕۆ',
        'total_debts'         => 'کۆی قەرزان',
        'total_stock'         => 'کۆی مالخانه‌',
        'today_transactions'  => 'مامەڵەی ئەمڕۆ',
        'today_total_paid'    => 'کۆی پارەدراوی ئەمڕۆ',
        'latest_sales'        => 'دوایین فرۆشتن',
        'no_sales_yet'        => 'هێشتا فرۆشتنێک نییە',

        // Inventory
        'total_pieces'       => 'کۆی یەکەکان',
        'stock_cost'         => 'لێچوونی مالخانه‌',
        'sell_value'         => 'بەهای فرۆشتن',
        'needs_restock'      => 'پێویستی کۆگا',
        'out_of_stock'       => 'مالخانه‌ تاڵی',
        'low_stock'          => 'مالخانه‌ کەم',
        'good_stock'         => 'مالخانه‌ باش',
        'stock_ok'           => 'مالخانه‌ باشە',
        'out_of_stock_badge' => 'تەواو',
        'low_badge'          => 'کەم',
        'available_badge'    => 'هەیە',
        'stock_report'       => 'ڕاپۆرتی مالخانه‌',
        'stock_value'        => 'بەهای مالخانه‌',
        'sorted_asc'         => 'ڕیزکراو لە کەمەوە',

        // Debts
        'total_debts_iqd'  => 'کۆی قەرزان (IQD)',
        'total_debts_usd'  => 'کۆی قەرزان (USD)',
        'open_debts'       => 'قەرزی کراوەکان',
        'no_open_debts'    => 'هیچ قەرزێکی کراوە نییە!',
        'all_complete'     => 'هەموو فرۆشتنەکان تەواوبوون.',
        'add_payment'      => 'پارەیەک زیاد بکە',
        'payment_history'  => 'مێژووی پارەکان',
        'amount'           => 'پارە',
        'payment'          => 'پارەیەک',

        // Products
        'products_list'    => 'لیستی شتەمەنیکان',
        'add_product'      => 'شتەمەنیەک زیادبکە',
        'search_product'   => 'بگەریە بۆ شتەمەنی',
        'no_products'      => 'هیچ شتەمەنیەک نییە!',
        'product_name'     => 'ناوی شتەمەنی',
        'edit_product'     => 'گوهرینی شتەمەنی',
        'add_product_new'  => 'شتەمەنیەکی نو زیادبکە',
        'cost_secret'      => 'نرخی لێچوون (نهێنی)',
        'price_for_customers' => 'نرخی بۆ مشتەریان',

        // Customers
        'customers_list'       => 'لیستی مشتەریان',
        'add_customer'         => 'مشتەریەک زیادبکە',
        'search_customer'      => 'بگەریە بۆ مشتەری',
        'no_customers'         => 'هیچ مشتەریەک نییە.',
        'preferred_currency'   => 'دراوی دڵخواز',
        'full_name'            => 'ناوی تەواو',
        'sales_count'          => 'فرۆشتن',
        'total_sales'          => 'کۆی فرۆشتن',
        'no_debt'              => 'قەرزی نییە',
        'no_debt_detail'       => 'ئەم مشتەریە قەرزی نییە',
        'sales_history'        => 'مێژووی فرۆشتن',
        'no_sales_for_customer'=> 'هیچ فرۆشتنێک نییە.',
        'new_sale'             => 'فرۆشتنی نو',
        'whatsapp_statement'   => 'پێرستی هەژمار بنێرە واتساپ',
        'edit_customer'        => 'گوهرینی مشتەری',
        'add_customer_new'     => 'مشتەریەکی نو زیادبکە',
        'optional'             => 'دڵخواز',
        'optional_notes'       => 'تێبینیی زیاتر...',

        // Sales
        'sales_list'          => 'لیستی فرۆشتن',
        'new_sale_form'       => 'فرۆشتنی نو',
        'no_sales'            => 'هیچ فرۆشتنێک نییە.',
        'payment_type'        => 'جۆری پارەدان',
        'cash_now'            => 'پارەدانی ئێستا',
        'pay_later'           => 'دواتر دەدات',
        'installment_pay'     => 'قستەکانەوە',
        'products_sold'       => 'شتەمەنیکانی فرۆشراو',
        'add_product_row'     => 'شتەمەنی زیادبکە',
        'select_product'      => 'شتەمەنیەک هەڵبژێرە',
        'grand_total'         => 'کۆی گشتی',
        'payment_details'     => 'وردەکاری پارەدان',
        'full_payment_now'    => 'هەموو پارەکە ئێستا دەدرێت.',
        'amount_paid_now'     => 'پارەی دراو ئێستا',
        'zero_full_debt'      => '0 = قەرزی تەواو',
        'remaining_balance'   => 'ماوەی قەرز:',
        'first_installment'   => 'یەکەمین قست (بیانە)',
        'num_installments'    => 'ژمارەی قستەکان',
        'interval'            => 'کاتی نێوان قستەکان',
        'weekly'              => 'هەفتەیەک جار (7 رووژ)',
        'biweekly'            => 'دوو هەفتەیەک جار',
        'monthly'             => 'مانگێک جار (30 رووژ)',
        'bimonthly'           => 'دوو مانگێک جار',
        'first_installment_date' => 'رووژی یەکەمین قست',
        'per_installment'     => 'هەر قستێک:',
        'installment_formula' => 'ماوە دوای بیانە ÷ ژمارەی قستەکان',
        'save_sale'           => 'فرۆشتنەکە پارابکە',
        'invoice'             => 'فاتووره‌',
        'sale_customer'       => 'مشتەری',
        'payment_type_label'  => 'جۆری پارەدان',
        'currency_label'      => 'دراو',
        'total_label'         => 'کۆی گشتی',
        'amount_paid_label'   => 'پارەی دراو',
        'outstanding_label'   => 'ماوەی قەرز',
        'settled'             => '✓ دراوکراو',
        'delete_sale'         => 'فرۆشتنەکە ژێببرە',
        'back_to_sales'       => '→ گەریانەوە بۆ فرۆشتن',
        'installment_plan'    => 'پلانی قستەکان',
        'num_install'         => 'ژمارەی قستەکان',
        'each_install'        => 'هەر قستێک',
        'first_install_date'  => 'یەکەمین قست',
        'period_days'         => 'ماوە',
        'days'                => 'رووژ',
        'invoice_total'       => 'کۆی گشتی:',
        'delete_confirm'      => 'ئایا دەتەوێ ئەم فرۆشتنە ژێببریت؟',

        // Confirm dialogs
        'confirm_delete_product'  => 'ئایا دەتەوێ ئەم شتەمەنیە ژێببریت؟',
        'confirm_delete_customer' => 'ئایا دەتەوێ ئەم مشتەریە ژێببریت؟',
    ],

];
